### ISSUE TITLE
full deployment code

### ISSUE THREAD

**Issue by CodeWorldChanged** [Haiyang-W/DSVT#71]
Thank you very much for your work and for releasing the partial deployment code for backbone 3d in tensorrt. It would be really helpful if you can share the unrefined full deployment code to 1107315077@qq.com. Thanks a lot for this!

**Comment by Haiyang-W** [comment]
I have sent it to your email. But I recommend you to use [fully tensorRT repo](https://github.com/jingyue202205/DSVT-AI-TRT).

**Comment by jacoblambert** [comment]
@Haiyang-W Thanks for your work.
Have you used that repository? They report very slow inference speed compared to your paper, and users report inconsistent inference results differing greatly from your paper. So I'm not sure it's good to recommend it. Their environment is old but still, very very far from your reported 27hz.

`one frame takes about 0.7 seconds on my laptop with Intel(R) Core(TM) i5-7300HQ and NVIDIA GeForce GTX 1050 Mobile(1050ti)`

As such, can I also ask for the full deployment code? I think everyone would appreciate if you share full deployment code in this repo, also since "The speeds provided in the paper are the results of full deployment", you should share it for reproducibility; I don't really understand the universality argument. If there is a reason you can't share it, I'd like to ask to please share it to me at jacob.lambert@g.sp.m.is.nagoya-u.ac.jp .

All the best.

**Comment by Haiyang-W** [comment]
> @Haiyang-W Thanks for your work. Have you used that repository? They report very slow inference speed compared to your paper, and users report inconsistent inference results differing greatly from your paper. So I'm not sure it's good to recommend it. Their environment is old but still, very very far from your reported 27hz.
> 
> `one frame takes about 0.7 seconds on my laptop with Intel(R) Core(TM) i5-7300HQ and NVIDIA GeForce GTX 1050 Mobile(1050ti)`
> 
> As such, can I also ask for the full deployment code? I think everyone would appreciate if you share full deployment code in this repo, also since "The speeds provided in the paper are the results of full deployment", you should share it for reproducibility; I don't really understand the universality argument. If there is a reason you can't share it, I'd like to ask to please share it to me at [jacob.lambert@g.sp.m.is.nagoya-u.ac.jp](mailto:jacob.lambert@g.sp.m.is.nagoya-u.ac.jp) .
> 
> All the best.

I haven't used this repo, but it looks pretty good. The GPU you deployed might be inferior; we deploy on 3090s, and all our experimental data is tested on 3090s. You can refer to the deployment code in our official repo; it should be very fast on a 3090. Regarding the Head, if you are familiar with TensorRT, you should be able to write the deployment code in a few hours. Our fully deployed code is quite messy and not refined, so it can only serve as a reference and probably can't be used directly. If you need it, I can send it to you, but I think you will still need to rewrite the head deployment.

Best,
Haiyang

**Comment by jacoblambert** [comment]
Thanks for you reply @Haiyang-W . I'll give the repo a try and let you know how it goes for future reference. Still I'd appreciate if you could share your code as reference because I'm not experienced with deployment; I think it'll greatly help with the learning process. If I get it to run and get good results, I'll make a PR.

Best,
Jacob

**Comment by Haiyang-W** [comment]
> Thanks for your reply @Haiyang-W . I'll give the other repo a try and let you know how it goes for future reference. Still I'd appreciate if you could share your code as reference because I'm not experienced with deployment and looking at your deployment code I think I'd have a hard with doing the head from scratch; I think it'll greatly help with the learning process. I'll look into TensorRT but If you have any other learning resources that'd be great. If I get it to run and get good results, I'll make a PR.
> 
> Best, Jacob

It has been sent to your email. Please combine it with the deployment method provided by our repo to deploy the head. 

Thanks for your potential deployment contribution and good luck.

Best,
Haiyang

**Comment by albertnew2012** [comment]
Hi @Haiyang-W  Thank you so much for the great work! Would you mind sharing your full deployment code with me? If I can make some progress on top of it, I’ll create a PR and make it available to the community, so others can access it without needing to request it via email. Many thanks

**Comment by Haiyang-W** [comment]
> [albertnew2012@gmail.com](mailto:albertnew2012@gmail.com)

Have sent it. :)

**Comment by GuoliangPeng** [comment]
@Haiyang-W Hello, thank you for your excellent work. I used DSVT-AI-TRT for deployment testing and found that the results of Python and C++were inconsistent, but I couldn't find the reason. Can you share your complete deployment code? I would like to research it, thank you very much。gl.peng@outlook.com
